# Flash drivers and SPI NOR support for nRF7002 DK
CONFIG_FLASH=y
CONFIG_SPI=y
CONFIG_SPI_NOR=y

CONFIG_BOOT_MAX_IMG_SECTORS=256

# Bootloader logging (optional, helpful for debugging)
CONFIG_MCUBOOT_LOG_LEVEL_INF=y

# Decrease footprint slightly to fit the added SPI drivers
CONFIG_SIZE_OPTIMIZATIONS=y

# Enable swap-based upgrades using move (no scratch partition needed)
CONFIG_BOOT_UPGRADE_ONLY=n
CONFIG_BOOT_SWAP_USING_MOVE=y
